import type{ Metadata } from "next";

 
 export const metadata: Metadata = {
  title: 'Create About Page',
  description: 'Generated by Description',
  keywords: ['About page','Jorge'],
}

export default function AboutPage () {
  return (
    <main className="flex flex-col items-center p-24">
      <span className="text-lg">Hola mundo</span>
     <span className="text-7xl">About Page </span> 
    </main>
  );
}


